<?php

namespace Database\Seeders;

use App\Domain\Components\Enums\ComponentType;
use App\Models\Component;
use App\Models\ComponentCategory;
use App\Models\User;
use Illuminate\Support\Str;

class ComponentCatalogSeeder
{
    public function run(User $owner): void
    {
        foreach ($this->catalog() as $categoryDefinition) {
            $category = ComponentCategory::factory()->create([
                'type' => $categoryDefinition['type'],
                'name' => $categoryDefinition['name'],
                'slug' => Str::slug($categoryDefinition['name']),
            ]);

            foreach ($categoryDefinition['components'] as $component) {
                Component::factory()->create([
                    'component_category_id' => $category->getKey(),
                    'name' => $component['name'],
                    'manufacturer' => $component['manufacturer'] ?? null,
                    'reference' => $component['reference'] ?? null,
                    'description' => $component['description'] ?? null,
                    'specs' => $component['specs'] ?? [],
                    'price_cents' => $component['price_cents'] ?? null,
                    'currency' => $component['currency'] ?? null,
                    'supplier_url' => $component['supplier_url'] ?? null,
                    'image_url' => $component['image_url'] ?? null,
                    'created_by' => $owner->getKey(),
                ]);
            }
        }
    }

    /**
     * @return list<array{type: string, name: string, components: list<array<string, mixed>>}>
     */
    private function catalog(): array
    {
        return [
            [
                'type' => ComponentType::Microcontroller->value,
                'name' => 'Cartes de développement',
                'components' => [
                    [
                        'name' => 'Arduino Uno R3',
                        'manufacturer' => 'Arduino',
                        'reference' => 'A000066',
                        'description' => 'Carte de développement à microcontrôleur ATmega328P, la plus utilisée et documentée de la famille Arduino pour le prototypage électronique.',
                        'specs' => ['microcontroleur' => 'ATmega328P', 'tension' => '5V', 'frequence' => '16 MHz', 'E/S numeriques' => '14 (dont 6 PWM)', 'memoire_flash' => '32 KB'],
                        'price_cents' => 2930,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://store.arduino.cc/products/arduino-uno-rev3',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Arduino_Uno_-_R3.jpg',
                    ],
                    [
                        'name' => 'Arduino Nano',
                        'manufacturer' => 'Arduino',
                        'reference' => 'A000005',
                        'description' => "Carte de développement compacte à microcontrôleur ATmega328, compatible plaque d'essai, utilisée pour des projets embarqués de petite taille.",
                        'specs' => ['microcontroleur' => 'ATmega328', 'tension' => '5V', 'frequence' => '16 MHz', 'E/S numeriques' => '22 (dont 6 PWM)', 'entrees_analogiques' => '8'],
                        'price_cents' => 2720,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://store.arduino.cc/products/arduino-nano',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Arduino_Nano.jpg',
                    ],
                    [
                        'name' => 'Arduino Mega 2560 Rev3',
                        'manufacturer' => 'Arduino',
                        'reference' => 'A000067',
                        'description' => "Carte de développement à microcontrôleur ATmega2560 offrant un grand nombre d'entrées/sorties pour des projets robotiques complexes.",
                        'specs' => ['microcontroleur' => 'ATmega2560', 'tension' => '5V', 'E/S numeriques' => '54 (dont 15 PWM)', 'entrees_analogiques' => '16', 'memoire_flash' => '256 KB'],
                        'price_cents' => 5280,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://store.arduino.cc/products/arduino-mega-2560-rev3',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Arduino_MEGA_2560_R3,_front_side.jpg',
                    ],
                    [
                        'name' => 'Arduino Leonardo',
                        'manufacturer' => 'Arduino',
                        'reference' => 'A000057',
                        'description' => "Carte de développement à microcontrôleur ATmega32u4 intégrant une communication USB native permettant d'émuler un clavier ou une souris.",
                        'specs' => ['microcontroleur' => 'ATmega32u4', 'tension' => '5V', 'frequence' => '16 MHz', 'E/S numeriques' => '20 (dont 7 PWM)', 'interface' => 'USB natif'],
                        'price_cents' => 2540,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://store.arduino.cc/products/arduino-leonardo-with-headers',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Arduino_Leonardo.jpg',
                    ],
                    [
                        'name' => 'Raspberry Pi 4 Model B',
                        'manufacturer' => 'Raspberry Pi Ltd',
                        'reference' => 'Raspberry Pi 4 Model B',
                        'description' => "Ordinateur monocarte à processeur quad-core capable de faire tourner un système d'exploitation complet, utilisé comme unité de contrôle avancée en robotique.",
                        'specs' => ['processeur' => 'Broadcom BCM2711 quad-core Cortex-A72', 'frequence' => '1.5 GHz', 'ram' => '2/4/8 GB LPDDR4', 'connectivite' => 'Wi-Fi ac, Bluetooth 5.0, Gigabit Ethernet', 'ports' => '2x USB 3.0, 2x USB 2.0, 2x micro-HDMI'],
                        'price_cents' => 10590,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.raspberrypi.com/products/raspberry-pi-4-model-b/',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Raspberry_Pi_4_Model_B_-_Top.jpg',
                    ],
                    [
                        'name' => 'Raspberry Pi Pico',
                        'manufacturer' => 'Raspberry Pi Ltd',
                        'reference' => 'Raspberry Pi Pico (RP2040)',
                        'description' => 'Microcontrôleur à faible coût basé sur la puce RP2040 conçue par Raspberry Pi, dual-core, programmable en C/C++ ou MicroPython.',
                        'specs' => ['microcontroleur' => 'RP2040 dual-core Cortex-M0+', 'frequence' => '133 MHz', 'ram' => '264 KB SRAM', 'memoire_flash' => '2 MB', 'interface' => 'USB 1.1'],
                        'price_cents' => 450,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.raspberrypi.com/products/raspberry-pi-pico/',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Raspberry_Pi_Pico_top_and_bottom.jpg',
                    ],
                    [
                        'name' => 'STM32 "Blue Pill"',
                        'manufacturer' => 'Generic',
                        'reference' => 'STM32F103C8T6',
                        'description' => 'Carte de développement bon marché basée sur le microcontrôleur STM32F103C8T6 (ARM Cortex-M3), populaire comme alternative économique à Arduino.',
                        'specs' => ['microcontroleur' => 'STM32F103C8T6 (Cortex-M3)', 'frequence' => '72 MHz', 'memoire_flash' => '64 KB', 'ram' => '20 KB', 'E/S' => '37 GPIO'],
                        'price_cents' => 350,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Blue_Pill.jpg',
                    ],
                    [
                        'name' => 'Teensy 4.0',
                        'manufacturer' => 'PJRC',
                        'reference' => 'Teensy 4.0',
                        'description' => 'Carte de développement compacte à processeur ARM Cortex-M7 très rapide (600 MHz), utilisée pour des applications embarquées exigeantes en performance.',
                        'specs' => ['processeur' => 'NXP iMXRT1062 Cortex-M7', 'frequence' => '600 MHz', 'ram' => '1024 KB', 'memoire_flash' => '1984 KB', 'E/S numeriques' => '40 broches'],
                        'price_cents' => 2890,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.pjrc.com/store/teensy40.html',
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::Microcontroller->value,
                'name' => 'Modules WiFi/BLE',
                'components' => [
                    [
                        'name' => 'ESP32-WROOM-32 DevKit',
                        'manufacturer' => 'Espressif Systems',
                        'reference' => 'ESP32-DevKitC',
                        'description' => "Carte de développement basée sur le SoC ESP32, intégrant Wi-Fi et Bluetooth, largement utilisée pour l'IoT et la robotique connectée.",
                        'specs' => ['processeur' => 'Xtensa LX6 dual-core', 'frequence' => '240 MHz', 'connectivite' => 'Wi-Fi 802.11 b/g/n + Bluetooth 4.x BLE', 'broches' => '38 GPIO', 'memoire_flash' => '4 MB'],
                        'price_cents' => 1500,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.espressif.com/en/products/devkits/esp32-devkitc/overview',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/ESP32_Espressif_ESP-WROOM-32_Dev_Board.jpg',
                    ],
                    [
                        'name' => 'ESP8266 NodeMCU',
                        'manufacturer' => 'Espressif Systems',
                        'reference' => 'NodeMCU v1.0 (ESP-12E)',
                        'description' => 'Carte de développement Wi-Fi basée sur le SoC ESP8266, très utilisée pour les objets connectés à faible coût.',
                        'specs' => ['processeur' => 'Tensilica L106 32-bit', 'frequence' => '160 MHz', 'connectivite' => 'Wi-Fi 802.11 b/g/n', 'E/S numeriques' => '11 GPIO', 'memoire_flash' => '4 MB'],
                        'price_cents' => 690,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/NodeMCU_DEVKIT_1.0.jpg',
                    ],
                ],
            ],
            [
                'type' => ComponentType::Sensor->value,
                'name' => 'Distance & proximité',
                'components' => [
                    [
                        'name' => 'HC-SR04',
                        'manufacturer' => 'Generic',
                        'reference' => 'HC-SR04',
                        'description' => "Capteur de distance à ultrasons mesurant la distance à un obstacle par mesure du temps d'écho, très utilisé en robotique pour l'évitement d'obstacles.",
                        'specs' => ['portee' => '2-400cm', 'tension' => '5V', 'interface' => 'Trigger/Echo (numerique)', 'frequence_ultrason' => '40 kHz', 'precision' => '~3mm'],
                        'price_cents' => 190,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/HC_SR04_Ultrasonic_Module.jpg',
                    ],
                    [
                        'name' => 'VL53L0X',
                        'manufacturer' => 'STMicroelectronics',
                        'reference' => 'VL53L0X',
                        'description' => 'Module de mesure de distance par temps de vol laser (940nm), offrant une mesure précise indépendante de la réflectivité de la cible.',
                        'specs' => ['portee' => "jusqu'à 2m", 'resolution' => '1mm', 'interface' => 'I2C', 'tension' => '2.6-5.5V', 'technologie' => 'Time-of-Flight laser 940nm'],
                        'price_cents' => 1200,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.st.com/en/imaging-and-photonics-solutions/vl53l0x.html',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Sharp GP2Y0A21YK0F',
                        'manufacturer' => 'Sharp',
                        'reference' => 'GP2Y0A21YK0F',
                        'description' => "Capteur de distance infrarouge analogique par triangulation, peu sensible à la couleur ou à la réflectivité de la cible, pour la détection d'obstacles de 10 à 80 cm.",
                        'specs' => ['portee' => '10-80cm', 'tension' => '4.5-5.5V', 'sortie' => 'analogique', 'courant' => '30mA', 'technologie' => 'triangulation infrarouge'],
                        'price_cents' => 1150,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.pololu.com/product/136',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Sharp_GP2Y0A21YK_IR_proximity_sensor_cropped.jpg',
                    ],
                ],
            ],
            [
                'type' => ComponentType::Sensor->value,
                'name' => 'Environnement',
                'components' => [
                    [
                        'name' => 'DHT11',
                        'manufacturer' => 'Aosong',
                        'reference' => 'DHT11',
                        'description' => "Capteur numérique de température et d'humidité bas de gamme, économique et simple d'intégration pour projets débutants.",
                        'specs' => ['tension' => '3.5-5.5V', 'plage_temperature' => '0-50°C ±2°C', 'plage_humidite' => '20-90% ±5%', 'interface' => '1 fil (numerique)', 'echantillonnage' => '1 Hz'],
                        'price_cents' => 390,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.mouser.com/datasheet/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Dht11_term_and_humidity_sensor.jpg',
                    ],
                    [
                        'name' => 'DHT22 (AM2302)',
                        'manufacturer' => 'Aosong',
                        'reference' => 'DHT22 / AM2302',
                        'description' => "Capteur numérique de température et d'humidité plus précis et à plage de mesure plus large que le DHT11.",
                        'specs' => ['tension' => '3.3-5.5V', 'plage_temperature' => '-40 à 80°C ±0.5°C', 'plage_humidite' => '0-100% ±2%', 'interface' => '1 fil (numerique)', 'echantillonnage' => '0.5 Hz'],
                        'price_cents' => 690,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://cdn-shop.adafruit.com/datasheets/Digital+humidity+and+temperature+sensor+AM2302.pdf',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'BMP280',
                        'manufacturer' => 'Bosch Sensortec',
                        'reference' => 'BMP280',
                        'description' => 'Capteur numérique de pression atmosphérique et de température, utilisé notamment comme altimètre barométrique.',
                        'specs' => ['tension' => '1.8-3.6V (module 3-5V)', 'plage_pression' => '300-1100 hPa', 'precision' => '±1 hPa', 'interface' => 'I2C/SPI', 'plage_temperature' => '-40 à 85°C'],
                        'price_cents' => 650,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.bosch-sensortec.com/media/boschsensortec/downloads/product_flyer/bst-bmp280-fl000.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/BMP280Sensor.jpg',
                    ],
                ],
            ],
            [
                'type' => ComponentType::Sensor->value,
                'name' => 'Mouvement & orientation',
                'components' => [
                    [
                        'name' => 'MPU6050 (GY-521)',
                        'manufacturer' => 'TDK InvenSense',
                        'reference' => 'MPU-6050 / GY-521',
                        'description' => "Centrale inertielle 6 axes combinant accéléromètre et gyroscope, largement utilisée pour la stabilisation et l'orientation en robotique.",
                        'specs' => ['axes' => '6 (3 gyroscope + 3 accelerometre)', 'plage_gyroscope' => '±250 à ±2000°/s', 'plage_accelerometre' => '±2g à ±16g', 'interface' => 'I2C', 'tension' => '3-5V (module)'],
                        'price_cents' => 1550,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.digikey.com/en/products/detail/tdk-invensense/MPU-6050/4038009',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/GY-521_MPU-6050_Module_3_Axis_Gyroscope_%2B_Accelerometer_0487.jpg',
                    ],
                    [
                        'name' => 'HC-SR501',
                        'manufacturer' => 'Generic',
                        'reference' => 'HC-SR501',
                        'description' => "Module détecteur de mouvement à infrarouge passif (PIR), utilisé pour la détection de présence humaine dans les systèmes d'alarme ou d'éclairage automatique.",
                        'specs' => ['tension' => '4.5-20V', 'portee' => '3-7m reglable', 'angle_detection' => '<120°', 'delai_sortie' => '0.3-200s reglable', 'sortie' => 'numerique 3.3V'],
                        'price_cents' => 250,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::Sensor->value,
                'name' => 'Force & position',
                'components' => [
                    [
                        'name' => 'HX711',
                        'manufacturer' => 'Avia Semiconductor',
                        'reference' => 'HX711',
                        'description' => 'Module amplificateur et convertisseur analogique-numérique 24 bits dédié à la lecture de jauges de contrainte (cellules de charge) pour la pesée.',
                        'specs' => ['resolution' => '24-bit', 'tension' => '2.7-5V', 'interface' => '2 fils (horloge/donnees)', 'gain' => '128/64 (voie A), 32 (voie B)', 'usage' => 'amplificateur de jauge de contrainte'],
                        'price_cents' => 1250,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.sparkfun.com/products/13879',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'TCRT5000',
                        'manufacturer' => 'Vishay',
                        'reference' => 'TCRT5000',
                        'description' => "Capteur optique réfléchissant infrarouge combinant émetteur et récepteur, utilisé pour la détection de ligne ou d'objets à faible distance.",
                        'specs' => ['portee' => '1-25mm', 'tension' => '3.3-5V', 'longueur_onde' => '950nm', 'sortie' => 'numerique (comparateur) avec potentiometre', 'courant_sortie' => '>15mA'],
                        'price_cents' => 200,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.vishay.com/docs/83760/tcrt5000.pdf',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Capteur à effet Hall (A3144 / KY-003)',
                        'manufacturer' => 'Allegro MicroSystems',
                        'reference' => 'A3144',
                        'description' => "Module capteur à effet Hall détectant la présence d'un champ magnétique, utilisé comme interrupteur magnétique numérique en robotique (ex : détection de rotation).",
                        'specs' => ['tension' => '4.5-24V (module 5V typique)', 'sortie' => 'numerique (collecteur ouvert)', 'puce' => 'A3144', 'type' => 'commutateur unipolaire non verrouillant'],
                        'price_cents' => 200,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Encodeur rotatif KY-040',
                        'manufacturer' => 'Generic',
                        'reference' => 'KY-040',
                        'description' => 'Module encodeur rotatif incrémental avec bouton-poussoir intégré, utilisé pour le réglage manuel de paramètres ou la navigation dans un menu.',
                        'specs' => ['tension' => '5V', 'resolution' => '20 impulsions/tour', 'type' => 'encodeur incrémental', 'sortie' => 'numerique (CLK/DT/SW)', 'bouton_poussoir' => 'integre'],
                        'price_cents' => 190,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::Actuator->value,
                'name' => 'Servomoteurs',
                'components' => [
                    [
                        'name' => 'Servomoteur SG90',
                        'manufacturer' => 'TowerPro',
                        'reference' => 'SG90',
                        'description' => 'Micro-servomoteur analogique 9 g à engrenages plastique, utilisé pour des mouvements angulaires légers en robotique et modélisme.',
                        'specs' => ['tension' => '4.8-6V', 'couple' => '1.6-2.2 kg.cm', 'vitesse' => '0.08-0.09s/60°', 'angle_rotation' => '180°', 'poids' => '9-10.5g'],
                        'price_cents' => 300,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.ee.ic.ac.uk/pcheung/teaching/DE1_EE/stores/sg90_datasheet.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Tower_Pro_SG90_micro_servo_motor.jpg',
                    ],
                    [
                        'name' => 'Servomoteur MG996R',
                        'manufacturer' => 'TowerPro',
                        'reference' => 'MG996R',
                        'description' => 'Servomoteur numérique à couple élevé et engrenages métalliques, utilisé pour des charges plus importantes que le SG90 (bras robotisés, direction RC).',
                        'specs' => ['tension' => '4.8-6.6V', 'couple' => '9.4-11 kg.cm', 'courant_marche' => '500mA', 'courant_blocage' => '2.5A (6V)', 'vitesse' => '0.15-0.19s/60°'],
                        'price_cents' => 700,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.handsontec.com/dataspecs/motor_fan/MG996R.pdf',
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::Actuator->value,
                'name' => 'Moteurs pas-à-pas',
                'components' => [
                    [
                        'name' => 'Moteur pas-à-pas NEMA17',
                        'manufacturer' => 'Generic',
                        'reference' => 'NEMA17',
                        'description' => 'Moteur pas-à-pas hybride bipolaire au format NEMA 17, largement utilisé dans les imprimantes 3D, machines CNC et projets robotiques nécessitant un positionnement précis.',
                        'specs' => ['angle_pas' => '1.8°', 'pas_par_tour' => '200', 'tension' => '12V (typique)', 'courant_par_phase' => '1-2A', 'couple_maintien' => '~40-45 N.cm'],
                        'price_cents' => 1200,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://reprap.org/wiki/NEMA_17_Stepper_motor',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Nema_17_Stepper_Motor.jpg',
                    ],
                    [
                        'name' => 'Moteur pas-à-pas 28BYJ-48',
                        'manufacturer' => 'Generic',
                        'reference' => '28BYJ-48',
                        'description' => 'Moteur pas-à-pas unipolaire 5V à réducteur intégré, très répandu chez les amateurs, généralement piloté par une carte à base de ULN2003.',
                        'specs' => ['tension' => '5V', 'courant_par_phase' => '~240mA', 'rapport_reduction' => '1:64 (approx.)', 'angle_pas' => '5.625°/64', 'pas_par_tour_sortie' => '~4096'],
                        'price_cents' => 250,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.mouser.com/datasheet/2/758/stepd-01-data-sheet-1143075.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/28BYJ-48_unipolar_stepper_motor_with_ULN2003_driver.jpg',
                    ],
                ],
            ],
            [
                'type' => ComponentType::Actuator->value,
                'name' => 'Moteurs DC & actionneurs',
                'components' => [
                    [
                        'name' => 'Motoréducteur TT',
                        'manufacturer' => 'Generic',
                        'reference' => 'TT Motor 1:48',
                        'description' => 'Motoréducteur à courant continu bon marché avec boîtier plastique jaune, à double arbre de sortie, très utilisé dans les kits de robots/voitures Arduino.',
                        'specs' => ['tension' => '3-6V', 'rapport_reduction' => '1:48', 'vitesse_a_vide' => '90 tr/min (3V) - 200-250 tr/min (6V)', 'courant_a_vide' => '~150-160mA', 'courant_blocage' => '1.1-1.5A'],
                        'price_cents' => 300,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.adafruit.com/product/3777',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Moteur à courant continu 775',
                        'manufacturer' => 'Generic',
                        'reference' => '775',
                        'description' => 'Moteur à courant continu de forte puissance au format 775, utilisé dans les outils électriques et projets robotiques nécessitant du couple et de la vitesse.',
                        'specs' => ['tension' => '12V (plage 6-20V selon modele)', 'vitesse_a_vide' => '5500-12000 tr/min', 'courant' => '0.55-1.2A', 'diametre' => '42.2mm', 'longueur' => '67-98mm'],
                        'price_cents' => 1200,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.handsontec.com/dataspecs/motor_fan/775-Motor.pdf',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Solénoïde push-pull 12V',
                        'manufacturer' => 'Generic',
                        'reference' => '12V Push-Pull',
                        'description' => "Électroaimant linéaire à commande 12V capable de pousser ou tirer un noyau mobile, utilisé pour des mécanismes de verrouillage ou d'actionnement simple.",
                        'specs' => ['tension' => '12V', 'course' => '10-20mm (variable)', 'force' => '3.5-45N (variable)', 'courant' => '~1.85-3A'],
                        'price_cents' => 1200,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.adafruit.com/product/413',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Vérin linéaire 12V (150mm)',
                        'manufacturer' => 'Generic',
                        'reference' => '150mm 12V',
                        'description' => "Vérin linéaire électrique 12V à vis et écrou entraînés par moteur à courant continu, avec fins de course intégrées, utilisé pour des mécanismes de levage ou d'inclinaison.",
                        'specs' => ['tension' => '12V', 'course' => '150mm (6 pouces)', 'vitesse' => '~10mm/s (typique)', 'force_poussee' => 'variable selon modele'],
                        'price_cents' => 3500,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::PreActuator->value,
                'name' => 'Pilotes de moteurs',
                'components' => [
                    [
                        'name' => 'Module driver L298N',
                        'manufacturer' => 'STMicroelectronics',
                        'reference' => 'L298N',
                        'description' => 'Module pont en H double, permettant de piloter deux moteurs à courant continu ou un moteur pas-à-pas en vitesse et en direction.',
                        'specs' => ['tension_logique' => '4.5-7V', 'tension_moteur' => '5-46V', 'courant_max_par_voie' => '2A', 'courant_crete' => '3A', 'puissance_max' => '25W'],
                        'price_cents' => 350,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.st.com/resource/en/datasheet/l298.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Dosmotorsl298n.jpg',
                    ],
                    [
                        'name' => 'Module driver L293D',
                        'manufacturer' => 'Texas Instruments',
                        'reference' => 'L293D',
                        'description' => 'Circuit intégré pont en H quadruple, permettant de piloter deux moteurs à courant continu en vitesse et en direction à partir de signaux logiques.',
                        'specs' => ['tension_logique' => '4.5-5V', 'tension_moteur' => '4.5-36V', 'courant_max_par_voie' => '600mA', 'courant_crete_par_voie' => '1.2A'],
                        'price_cents' => 250,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.ti.com/product/L293D',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/L293D_motor_driver_module.jpg',
                    ],
                    [
                        'name' => 'Module driver A4988',
                        'manufacturer' => 'Allegro MicroSystems',
                        'reference' => 'A4988',
                        'description' => 'Module driver pour moteur pas-à-pas bipolaire avec micro-pas réglable, régulation de courant et protections intégrées, très utilisé sur imprimantes 3D et CNC.',
                        'specs' => ['tension_moteur' => '8-35V', 'tension_logique' => '3-5.5V', 'courant_max_par_phase' => '2A (avec refroidissement)', 'micro_pas' => '1, 1/2, 1/4, 1/8, 1/16'],
                        'price_cents' => 400,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.pololu.com/file/0j450/a4988_dmos_microstepping_driver_with_translator.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/A4988_stepper_motor_driver.jpg',
                    ],
                    [
                        'name' => 'Module driver DRV8825',
                        'manufacturer' => 'Texas Instruments',
                        'reference' => 'DRV8825',
                        'description' => "Module driver pour moteur pas-à-pas bipolaire supportant le micro-pas jusqu'à 1/32, offrant plus de courant et de résolution que l'A4988.",
                        'specs' => ['tension_moteur' => '8.2-45V', 'courant_max_par_phase' => '2.2A (avec refroidissement)', 'micro_pas' => '1 a 1/32', 'protections' => 'surchauffe, surintensite, sous-tension'],
                        'price_cents' => 500,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.ti.com/lit/ds/symlink/drv8825.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/DRV8825_stepper_motor_controller_carrier.jpg',
                    ],
                    [
                        'name' => 'Module driver TB6600',
                        'manufacturer' => 'Toshiba',
                        'reference' => 'TB6600',
                        'description' => "Module driver de puissance pour moteur pas-à-pas bipolaire, supportant des courants plus élevés que l'A4988/DRV8825, courant sur imprimantes 3D et CNC de plus grande taille.",
                        'specs' => ['tension_alimentation' => '9-42V', 'courant_max_par_phase' => '4-4.5A', 'signal_logique' => '5V direct, 12V via resistance 1k'],
                        'price_cents' => 900,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Carte driver ULN2003',
                        'manufacturer' => 'Toshiba',
                        'reference' => 'ULN2003',
                        'description' => 'Carte à transistors Darlington ULN2003, utilisée comme interface de puissance pour piloter le moteur pas-à-pas 28BYJ-48 depuis un microcontrôleur.',
                        'specs' => ['tension' => '5V', 'canaux' => '4 (sur 7 disponibles)', 'courant_max_par_canal' => '500mA', 'tension_max_par_canal' => '50V'],
                        'price_cents' => 150,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://lastminuteengineers.com/28byj48-stepper-motor-arduino-tutorial/',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/ULN2003_unioplar_stepper_motor_driver_module.jpg',
                    ],
                ],
            ],
            [
                'type' => ComponentType::PreActuator->value,
                'name' => 'Commutation',
                'components' => [
                    [
                        'name' => 'Module relais 5V 1 canal',
                        'manufacturer' => 'Songle',
                        'reference' => 'SRD-05VDC-SL-C',
                        'description' => "Module relais 1 canal piloté en 5V, permettant de commuter des charges de puissance (jusqu'à 250V AC / 10A) depuis un signal logique de microcontrôleur.",
                        'specs' => ['tension_bobine' => '5V', 'courant_declenchement' => '~70-80mA', 'tension_max_commutee' => '250V AC / 30V DC', 'courant_max_commute' => '10A'],
                        'price_cents' => 200,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/SRD-05VDC-SL-C%205V%20one-channel%20relay%20module.jpg',
                    ],
                    [
                        'name' => 'Module driver MOSFET IRF520',
                        'manufacturer' => 'Vishay',
                        'reference' => 'IRF520',
                        'description' => "Module à base de MOSFET IRF520 permettant de commuter des charges de forte puissance (moteurs, LED, relais) à partir d'un signal logique 3.3V/5V.",
                        'specs' => ['tension_logique' => '3.3-5V', 'tension_commutee_max' => '24V (typique module)', 'courant_max' => '~5A (module)'],
                        'price_cents' => 200,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::EnergySource->value,
                'name' => 'Piles & accumulateurs',
                'components' => [
                    [
                        'name' => 'Élément Li-ion 18650',
                        'manufacturer' => 'Samsung SDI',
                        'reference' => 'INR18650-25R',
                        'description' => "Élément rechargeable lithium-ion cylindrique au format 18650, couramment utilisé comme cellule d'alimentation pour outils, lampes et robots.",
                        'specs' => ['tension_nominale' => '3.6V', 'capacite' => '2500mAh', 'courant_decharge_continu' => '20A', 'diametre' => '18.4mm', 'longueur' => '65.0mm'],
                        'price_cents' => 350,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.nkon.nl/en/samsung-18650-inr18650-25r.html',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/LiIon-18650-match.jpg',
                    ],
                    [
                        'name' => 'Batterie LiPo 2200mAh 3S',
                        'manufacturer' => 'Generic',
                        'reference' => '2200mAh 3S 35C',
                        'description' => 'Batterie lithium-polymère 3 cellules utilisée pour alimenter des modèles réduits RC, drones et robots nécessitant une forte puissance instantanée.',
                        'specs' => ['tension' => '11.1V', 'capacite' => '2200mAh', 'taux_decharge' => '35C', 'connecteur' => 'XT60 ou T-Connector', 'poids' => '185g'],
                        'price_cents' => 2200,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://motionrc.com/products/admiral-2200mah-3s-11-1v-35c-lipo-battery-with-t-connector-epr22003',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Pile alcaline 9V',
                        'manufacturer' => 'Generic',
                        'reference' => '6LR61',
                        'description' => "Pile alcaline 9V au format PP3, utilisée comme source d'alimentation compacte pour capteurs, multimètres et petits circuits robotiques.",
                        'specs' => ['tension' => '9V', 'chimie' => 'alcaline (Zn/MnO2)', 'impedance' => '1700 mOhm', 'poids' => '46g', 'dimensions' => '48.5x26.5x17.5mm'],
                        'price_cents' => 350,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://docs.rs-online.com/594f/0900766b81249808.pdf',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Energizer_9v_PP3_Alkaline_battery.jpg',
                    ],
                    [
                        'name' => 'Pack 4xAA avec support',
                        'manufacturer' => 'Generic',
                        'reference' => '4xAA Holder',
                        'description' => "Ensemble de quatre piles AA associées à un support (boîtier avec interrupteur), utilisé comme bloc d'alimentation basique 6V pour circuits et petits robots.",
                        'specs' => ['tension_sortie' => '6V (4x1.5V)', 'type_pile' => 'AA (LR6)', 'interrupteur' => 'oui', 'longueur_fils' => 'environ 15cm'],
                        'price_cents' => 500,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/4-AA_Battery_Holder,_Enclosed_with_Switch.jpg',
                    ],
                    [
                        'name' => 'Batterie plomb étanche 12V 7Ah',
                        'manufacturer' => 'Generic',
                        'reference' => '12V7Ah',
                        'description' => "Batterie au plomb étanche (VRLA/AGM) rechargeable, utilisée pour l'alimentation d'onduleurs, d'alarmes ou de bases mobiles robotiques nécessitant une réserve d'énergie importante.",
                        'specs' => ['tension' => '12V', 'capacite' => '7Ah (20h rate)', 'technologie' => 'AGM/VRLA', 'poids' => '2.25kg', 'dimensions' => '151x65x94mm'],
                        'price_cents' => 2500,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.batterymart.com/p-12v-7ah-sealed-lead-acid-battery.html',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/12V_7.5_Ah_Lead_Acid_Battery.JPG',
                    ],
                ],
            ],
            [
                'type' => ComponentType::EnergySource->value,
                'name' => 'Production & gestion',
                'components' => [
                    [
                        'name' => 'Panneau solaire 6V',
                        'manufacturer' => 'Generic',
                        'reference' => '6V 1-2W',
                        'description' => 'Petit panneau solaire polycristallin 6V destiné aux projets DIY et à la recharge de petites batteries ou circuits robotiques autonomes.',
                        'specs' => ['tension' => '6V', 'puissance' => '1-2W', 'courant' => 'environ 180-330mA', 'dimensions' => '136x110mm', 'epaisseur' => '3mm'],
                        'price_cents' => 900,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.adafruit.com/product/3809',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Régulateur buck LM2596',
                        'manufacturer' => 'Texas Instruments',
                        'reference' => 'LM2596',
                        'description' => "Module régulateur de tension abaisseur (buck) à base de circuit LM2596, permettant de convertir une tension d'entrée continue en une tension de sortie régulée inférieure pour alimenter des cartes robotiques.",
                        'specs' => ['tension_entree' => '4-40V (46V max)', 'tension_sortie' => '1.25-35V (reglable)', 'courant_sortie_max' => '3A', 'rendement' => "jusqu'à 92%", 'dimensions' => '43x21x14mm'],
                        'price_cents' => 300,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.ti.com/product/LM2596',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/LM2596_buck_converter_module,_MP1584_buck_converter_module,_and_SDB628_boost_converter_module.jpg',
                    ],
                ],
            ],
            [
                'type' => ComponentType::Effector->value,
                'name' => 'Effecteurs terminaux',
                'components' => [
                    [
                        'name' => 'Pince robotique (gripper) MG996R',
                        'manufacturer' => 'Generic',
                        'reference' => 'MG996R Claw Kit',
                        'description' => "Pince robotique (effecteur terminal) en aluminium actionnée par un servomoteur MG996R, utilisée pour la préhension d'objets sur un bras robotique.",
                        'specs' => ['servo' => 'MG996R (4.8-7.2V)', 'couple' => '13 kg.cm a 4.8V / 15 kg.cm a 6V', 'ouverture_max' => '50mm', 'poids' => '60g', 'materiau' => 'alliage aluminium'],
                        'price_cents' => 2000,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://thinkrobotics.com/products/mechanical-claw-for-robot-arm-with-mg996r-servo-online',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Roue 65mm pour moteur TT',
                        'manufacturer' => 'Generic',
                        'reference' => '65mm TT Wheel',
                        'description' => 'Roue caoutchoutée compatible avec les moto-réducteurs TT, utilisée comme organe de locomotion (effecteur de déplacement) sur les petits robots mobiles.',
                        'specs' => ['diametre' => '65mm', 'diametre_exterieur_pneu' => '67.5mm', 'largeur_pneu' => '26.6mm', 'poids' => '31.5g', 'compatibilite' => 'arbre hexagonal moteur TT'],
                        'price_cents' => 300,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.kiwi-electronics.com/en/thin-white-wheel-for-tt-motor-65mm-10319',
                        'image_url' => null,
                    ],
                ],
            ],
            [
                'type' => ComponentType::Effector->value,
                'name' => 'Indicateurs',
                'components' => [
                    [
                        'name' => 'LED 5mm rouge',
                        'manufacturer' => 'Generic',
                        'reference' => 'T-1 3/4 (5mm)',
                        'description' => 'Diode électroluminescente standard de 5mm, utilisée comme indicateur visuel de sortie (état, alerte) sur circuits et robots.',
                        'specs' => ['tension_directe' => '1.8-2.0V', 'courant_nominal' => '20mA', 'longueur_onde' => '643nm', 'intensite_lumineuse' => '75mcd', 'diametre' => '5mm'],
                        'price_cents' => 40,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.sparkfun.com/led-basic-red-5mm.html',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/LED,_5mm,_red_(unlabelled,_full).svg',
                    ],
                    [
                        'name' => 'Bandeau LED RGB WS2812B',
                        'manufacturer' => 'Worldsemi',
                        'reference' => 'WS2812B 60/m',
                        'description' => 'Bande de LED RGB adressables individuellement (type NeoPixel), pilotée par un seul fil de données, utilisée comme effecteur lumineux/indicateur sur les robots.',
                        'specs' => ['tension' => '5V', 'densite_led' => '60 LED/m', 'protocole' => '1 fil (data in/out)', 'profondeur_couleur' => '24 bits (16M couleurs)', 'consommation' => "jusqu'à 18W/m a pleine luminosite"],
                        'price_cents' => 1500,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.pololu.com/product/2547',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/Silicone_Sheath_NeoPixel_LED_Strip.jpg',
                    ],
                    [
                        'name' => 'Buzzer piézoélectrique actif 5V',
                        'manufacturer' => 'Generic',
                        'reference' => '5V Active Buzzer',
                        'description' => "Buzzer piézoélectrique actif fonctionnant sous 5V, utilisé comme indicateur sonore d'alerte ou de confirmation sur circuits robotiques.",
                        'specs' => ['tension' => '4-8V (nominal 5V)', 'frequence' => '2300 ±300 Hz', 'niveau_sonore' => '85dB a 10cm', 'courant_max' => '32mA', 'diametre' => '11.78mm'],
                        'price_cents' => 150,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.addicore.com/products/active-buzzer-5v',
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/2007-07-24_Piezoelectric_buzzer.jpg',
                    ],
                    [
                        'name' => 'Haut-parleur 8 ohms 0.5W',
                        'manufacturer' => 'Generic',
                        'reference' => '8ohm 0.5W',
                        'description' => 'Petit haut-parleur 8 ohms de faible puissance, utilisé comme effecteur/indicateur sonore dans les projets robotiques et électroniques DIY.',
                        'specs' => ['impedance' => '8 ohms', 'puissance' => '0.5W', 'diametre' => '50mm', 'hauteur' => '16mm', 'plage_frequence' => 'environ 600Hz-10kHz'],
                        'price_cents' => 250,
                        'currency' => 'EUR',
                        'supplier_url' => 'https://www.sparkfun.com/speaker-0-5w-8-ohm.html',
                        'image_url' => null,
                    ],
                    [
                        'name' => 'Écran LCD 16x2',
                        'manufacturer' => 'Generic',
                        'reference' => '16x2 HD44780',
                        'description' => "Écran LCD alphanumérique 16 colonnes x 2 lignes, piloté par un contrôleur compatible HD44780, utilisé comme indicateur d'affichage de texte sur les robots et projets embarqués.",
                        'specs' => ['resolution' => '16x2 caracteres', 'controleur' => 'compatible HD44780', 'tension' => '5V', 'interface' => 'parallele 4/8 bits (+ I2C via module optionnel)', 'retroeclairage' => 'LED'],
                        'price_cents' => 500,
                        'currency' => 'EUR',
                        'supplier_url' => null,
                        'image_url' => 'https://commons.wikimedia.org/wiki/Special:FilePath/MELT_16x2_LCD_alphanumeric_display_07(DXO).jpg',
                    ],
                ],
            ],
        ];
    }
}
