import ProjectForm from '@/Components/projects/ProjectForm'
import { ProjectStatusBadge } from '@/Components/ui/ProjectStatusBadge'
import AppLayout from '@/Layouts/AppLayout'
import type { Project, ProjectStatus, RobotType } from '@/types/projects'
import { Head, router } from '@inertiajs/react'
import { Archive, RotateCcw, Trash2 } from 'lucide-react'

interface SettingsProps { project: Project; robotTypes: RobotType[]; statuses: ProjectStatus[]; canManage: boolean; canArchive: boolean; canDelete: boolean }
export default function Settings({ project, robotTypes, statuses, canManage, canArchive, canDelete }: SettingsProps) {
    const confirmAndSend = (message: string, action: () => void) => { if (window.confirm(message)) action() }
    const archivePath = `/projects/${project.id}/${project.status === 'archived' ? 'restore' : 'archive'}`
    return <AppLayout project={project} breadcrumbs={[{ label: 'Mes projets', href: '/projects' }, { label: project.name, href: `/projects/${project.id}` }, { label: 'Paramètres' }]}><Head title={`Paramètres · ${project.name}`} /><section className="rf-form-page"><div className="rf-page-intro"><p className="rf-eyebrow">Projet</p><h1>Paramètres</h1><p>Gérez les informations et le cycle de vie de <strong>{project.name}</strong>.</p></div>{canManage ? <div className="rf-panel"><ProjectForm project={project} robotTypes={robotTypes} statuses={statuses} submitLabel="Enregistrer les modifications" onSubmit={(form) => form.put(`/projects/${project.id}`)} /></div> : <div className="rf-panel"><ProjectStatusBadge status={project.status} /><p>Vous pouvez consulter ce projet, mais vous ne disposez pas des droits de modification.</p></div>}{canArchive && <div className="rf-danger-panel"><div><h2>{project.status === 'archived' ? 'Restaurer le projet' : 'Archiver le projet'}</h2><p>{project.status === 'archived' ? 'Le projet redeviendra un brouillon actif.' : 'Le projet restera consultable, mais sera retiré des projets actifs.'}</p></div><button className="rf-button rf-button--secondary" onClick={() => confirmAndSend('Confirmer cette action ?', () => router.patch(archivePath))}>{project.status === 'archived' ? <><RotateCcw size={15} />Restaurer</> : <><Archive size={15} />Archiver</>}</button></div>}{canDelete && <div className="rf-danger-panel rf-danger-panel--delete"><div><h2>Zone dangereuse</h2><p>La suppression masque le projet et ses données dans l’application. Cette action est réservée au propriétaire.</p></div><button className="rf-button rf-button--danger" onClick={() => confirmAndSend(`Supprimer définitivement « ${project.name} » ?`, () => router.delete(`/projects/${project.id}`))}><Trash2 size={15} />Supprimer</button></div>}</section></AppLayout>
}
